### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: relation "messages" already exists

### ISSUE THREAD

**Issue by AnwarMohamed** [WhisperSystems/TextSecure-Server#42]
I am getting this error when trying to migrate accounts database
```
java -jar server/target/TextSecureServer-0.54.jar accountdb migrate tsconfig.yml 
```

```
root@root:~$ java -jar server/target/TextSecureServer-0.54.jar accountdb migrate tsconfig.yml 
INFO  [2015-07-01 17:13:28,021] liquibase: Successfully acquired change log lock
WARN  [2015-07-01 17:13:28,568] liquibase: accountsdb.xml is using schema version 2.0 rather than version 3.1
INFO  [2015-07-01 17:13:28,610] liquibase: Reading from public.databasechangelog
INFO  [2015-07-01 17:13:28,619] liquibase: Reading from public.databasechangelog
INFO  [2015-07-01 17:13:28,641] liquibase: Reading from public.databasechangelog
Exception in thread "main" INFO  [2015-07-01 17:13:28,647] liquibase: accountsdb.xml: 2::matt: Reading from public.databasechangelog
INFO  [2015-07-01 17:13:28,650] liquibase: accountsdb.xml: 2::matt: Columns data(json) added to accounts
INFO  [2015-07-01 17:13:28,652] liquibase: accountsdb.xml: 2::matt: Custom SQL executed
INFO  [2015-07-01 17:13:28,652] liquibase: accountsdb.xml: 2::matt: Custom SQL executed
INFO  [2015-07-01 17:13:28,653] liquibase: accountsdb.xml: 2::matt: Custom SQL executed
INFO  [2015-07-01 17:13:28,654] liquibase: accountsdb.xml: 2::matt: Null constraint has been added to accounts.data
INFO  [2015-07-01 17:13:28,654] liquibase: accountsdb.xml: 2::matt: Column accounts.auth_token dropped
INFO  [2015-07-01 17:13:28,655] liquibase: accountsdb.xml: 2::matt: Column accounts.salt dropped
liquibase.exception.MigrationFailedException: Migration failed for change set accountsdb.xml::2::matt:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE public.messages (id BIGSERIAL NOT NULL, account_id BIGINT NOT NULL, device_id BIGINT NOT NULL, encrypted_message TEXT NOT NULL, CONSTRAINT PK_MESSAGES PRIMARY KEY (id)): ERROR: relation "messages" already exists
INFO  [2015-07-01 17:13:28,656] liquibase: accountsdb.xml: 2::matt: Column accounts.signaling_key dropped
INFO  [2015-07-01 17:13:28,656] liquibase: accountsdb.xml: 2::matt: Column accounts.gcm_id dropped
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:388)INFO  [2015-07-01 17:13:28,656] liquibase: accountsdb.xml: 2::matt: Column accounts.apn_id dropped

	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40)
INFO  [2015-07-01 17:13:28,657] liquibase: accountsdb.xml: 2::matt: Column accounts.supports_sms dropped
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:64)
	at liquibase.Liquibase.update(Liquibase.java:202)INFO  [2015-07-01 17:13:28,658] liquibase: accountsdb.xml: 2::matt: Custom SQL executed

	at liquibase.Liquibase.update(Liquibase.java:181)INFO  [2015-07-01 17:13:28,658] liquibase: accountsdb.xml: 2::matt: Custom SQL executed

	at org.whispersystems.textsecuregcm.liquibase.DbMigrateCommand.run(DbMigrateCommand.java:60)
INFO  [2015-07-01 17:13:28,663] liquibase: accountsdb.xml: 2::matt: Columns device_id(bigint) added to keys
	at org.whispersystems.textsecuregcm.liquibase.NameableDbCommand.run(NameableDbCommand.java:42)
	at org.whispersystems.textsecuregcm.liquibase.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:49)INFO  [2015-07-01 17:13:28,668] liquibase: accountsdb.xml: 2::matt: Table pending_devices created

	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:72)
	at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:278)
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE public.messages (id BIGSERIAL NOT NULL, account_id BIGINT NOT NULL, device_id BIGINT NOT NULL, encrypted_message TEXT NOT NULL, CONSTRAINT PK_MESSAGES PRIMARY KEY (id)): ERROR: relation "messages" already exists
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:61)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:106)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1189)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1172)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:352)
	... 11 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "messages" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:366)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:294)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:54)
	... 15 more
ERROR [2015-07-01 17:13:28,673] liquibase: accountsdb.xml: 2::matt: Change Set accountsdb.xml::2::matt failed.  Error: Error executing SQL CREATE TABLE public.messages (id BIGSERIAL NOT NULL, account_id BIGINT NOT NULL, device_id BIGINT NOT NULL, encrypted_message TEXT NOT NULL, CONSTRAINT PK_MESSAGES PRIMARY KEY (id)): ERROR: relation "messages" already exists
! org.postgresql.util.PSQLException: ERROR: relation "messages" already exists
! at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[TextSecureServer-0.54.jar:0.54]
! at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[TextSecureServer-0.54.jar:0.54]
! at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[TextSecureServer-0.54.jar:0.54]
! at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[TextSecureServer-0.54.jar:0.54]
! at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374) ~[TextSecureServer-0.54.jar:0.54]
! at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:366) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:294) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:54) ~[TextSecureServer-0.54.jar:0.54]
! ... 15 common frames omitted
! Causing: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE public.messages (id BIGSERIAL NOT NULL, account_id BIGINT NOT NULL, device_id BIGINT NOT NULL, encrypted_message TEXT NOT NULL, CONSTRAINT PK_MESSAGES PRIMARY KEY (id)): ERROR: relation "messages" already exists
! at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:61) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:106) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1189) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1172) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.changelog.ChangeSet.execute(ChangeSet.java:352) ~[TextSecureServer-0.54.jar:0.54]
! at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:40) [TextSecureServer-0.54.jar:0.54]
! at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:64) [TextSecureServer-0.54.jar:0.54]
! at liquibase.Liquibase.update(Liquibase.java:202) [TextSecureServer-0.54.jar:0.54]
! at liquibase.Liquibase.update(Liquibase.java:181) [TextSecureServer-0.54.jar:0.54]
! at org.whispersystems.textsecuregcm.liquibase.DbMigrateCommand.run(DbMigrateCommand.java:60) [TextSecureServer-0.54.jar:0.54]
! at org.whispersystems.textsecuregcm.liquibase.NameableDbCommand.run(NameableDbCommand.java:42) [TextSecureServer-0.54.jar:0.54]
! at org.whispersystems.textsecuregcm.liquibase.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:49) [TextSecureServer-0.54.jar:0.54]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [TextSecureServer-0.54.jar:0.54]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [TextSecureServer-0.54.jar:0.54]
! at io.dropwizard.Application.run(Application.java:72) [TextSecureServer-0.54.jar:0.54]
! at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:278) [TextSecureServer-0.54.jar:0.54]
INFO  [2015-07-01 17:13:28,677] liquibase: accountsdb.xml::2::matt: Successfully released change log lock

```

**Comment by moxie0** [comment]
sorry this isn't a support forum, or a supported product
